version: '3.9'

services:

  db:
    container_name: parking-control-db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=parking-control-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=abc123
    ports:
      - '5432:5432'